-- AlterTable
ALTER TABLE "weekly_summary" ADD COLUMN "daysWithJapa20" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "weekly_summary" ADD COLUMN "daysWithMp20" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "weekly_summary" ADD COLUMN "daysWithSleep20" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "weekly_summary" ADD COLUMN "daysWithWake20" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "weekly_summary" ADD COLUMN "totalLectureHours" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "weekly_summary" ADD COLUMN "totalReadingHours" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "weekly_summary" ADD COLUMN "totalStudyWorkHours" DOUBLE PRECISION NOT NULL DEFAULT 0;
